services:
  api:
    container_name: evolution_api
    image: atendai/evolution-api:v2.2.0
    restart: always
    environment:
      - DATABASE_PROVIDER=postgresql  # These can also be explicitly set if needed
      - DATABASE_CONNECTION_URI=postgresql://postgres:Shadow151@postgres-evo:5432/evolution?schema=public
    depends_on:
      - redis
      - postgres
    ports:
      - 8090:8080
    volumes:
      - evolution_instances:/evolution/instances
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - 8090

  redis:
    image: redis:latest
    networks:
      - evolution-net
    container_name: redis-evo
    command: >
      redis-server --port 6379 --appendonly yes
    volumes:
      - evolution_redis:/data
    ports:
      - 6380:6379

  postgres:
    container_name: postgres-evo
    image: postgres:15
    networks:
      - evolution-net
    command: ["postgres", "-c", "max_connections=1000"]
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=Shadow151
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5433

volumes:
  evolution_instances:
  evolution_redis:
  postgres_data:


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
