services:
  evolution_api:
    image: atendai/evolution-api:v2.2.0
    env_file:
      - .env  # This ensures the .env file is loaded correctly
    environment:
      - DATABASE_PROVIDER=postgresql  # These can also be explicitly set if needed
      - DATABASE_CONNECTION_URI=postgresql://postgres:Shadow151@postgres:5432/evolution?schema=public
    networks:
      - evolution-net
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shadow151
      POSTGRES_DB: evolution
    networks:
      - evolution-net

  redis:
    image: redis:latest
    networks:
      - evolution-net

networks:
  evolution-net:
    driver: bridge
