version: '3'

services:
  evolution_api:
    image: evolution_api_image
    environment:
      - DATABASE_CONNECTION_URI=postgresql://postgres:Shadow151!@postgres:5432/evolution
      - CACHE_REDIS_URI=redis://redis:6379
    networks:
      - coolify_network
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shadow151
      POSTGRES_DB: evolution
    networks:
      - coolify_network

  redis:
    image: redis:latest
    networks:
      - coolify_network

networks:
  coolify_network:
    driver: bridge
