services:
  evolution_api:
    image: atendai/evolution-api:v2.2.0
    environment:
      - DATABASE_CONNECTION_URI=postgresql://postgres:Shadow151!@postgres:5432/evolution
      - CACHE_REDIS_URI=redis://redis:6379
    networks:
      - evolutin-net
    depends_on:
      - postgres
      - redis
    env_file:
      - .env

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shadow151
      POSTGRES_DB: evolution
    networks:
      - evolution-net

  redis:
    image: redis:latest
    networks:
      - evolution-net

networks:
  evolution-net:
    driver: bridge
